# Generated by Django 4.0 on 2023-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupTassApp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotDuMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('post', models.CharField(max_length=100)),
            ],
        ),
    ]
